baseURL = "https://purerob.com"
languageCode = "en-us"
title = "purerob"
theme = "ananke"

[params]
  author = "Rob Quast"
  description = "Welcome to purerob.com!"
  favicon = ""
  background_color_class = "bg-gradient-to-r from-orange-100 to-teal-200"
  recent_posts_number = 5
  mainImage = "images/photo.png"
  primary_color = "#ff6600"  # A punchy orange
  secondary_color = "#008080"  # Teal

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "/projects"
  weight = 2